export const filterKeywordsMap: Record<string, string[]> = {
  humanoid: ["humanoid"],
  beast: ["beast"],
  undead: ["undead"],
  dragon: ["dragon"],
  giant: ["giant"],
  warrior: ["warrior", "fighter", "barbarian", "paladin", "monk"],
  mage: ["mage", "wizard", "sorcerer", "warlock"],
  rogue: ["rogue", "thief", "assassin", "bard"],
  cleric: ["cleric", "priest", "druid"],
  ranger: ["ranger", "hunter"],
  melee: ["melee", "sword", "axe", "mace", "dagger", "spear", "reach"],
  ranged: ["ranged", "bow", "crossbow", "thrown", "ammunition"],
  magic: ["magic", "spell", "arcane", "wand", "staff", "focus", "enchanted"],
  siege: ["siege", "ballista", "cannon", "catapult"],
  light: ["light"],
  medium: ["medium"],
  heavy: ["heavy"],
  shields: ["shield"],
  offensive: ["offensive", "damage", "attack"],
  defensive: ["defensive", "ward", "protection"],
  utility: ["utility", "utility spell", "support"],
  healing: ["healing", "heal"],
};
